[Unit]
Description=DESCRIPTION
# Documentation=DOCUMENTATION
After=network.target
# PartOf=GROUP

[Service]
Type=simple
User=USER
WorkingDirectory=PROJECT_DIR
ExecStart=/usr/bin/make -C PROJECT_DIR run
# -- Optional:
# ExecStart=/bin/bash -c "cd PROJECT_DIR && make run"
# -- Set Environment:
# Environment=VARIABLE=value
# EnvironmentFile=PROJECT_DIR/.env
Restart=always
StandardOutput=file:SYSTEMDIR/records.log
StandardError=file:SYSTEMDIR/errors.log

[Install]
WantedBy=multi-user.target
